### ISSUE TITLE
TV4 channels - enhance look and feel

### ISSUE THREAD

**Issue by matsarv** [retrospect-addon/plugin.video.retrospect#1271]
### Is your feature request related to a problem? Please describe

No problem, just some small enhancements for a great product.

### Describe the solution you'd like

Some minor enhancement are requested and I will provide code for the requested changes below that I use on my own system.

- Add info on when episode expire. (also in #1269)
- Add three dots to extra folders.
- Change display name for program title.
- Display Fanart to Program, Season and Episodes. (also in #1268)
- Add Tags to TvShows.
- Change Swedish language file strings.po
- Remove date on program folder name list.

All requested changes are visualized in the images and the code below.

![change1](https://user-images.githubusercontent.com/46671821/71561558-91df6400-2a78-11ea-88db-fdee78ca4198.png)

![change2](https://user-images.githubusercontent.com/46671821/71561561-986ddb80-2a78-11ea-9400-2c91191ffb26.png)

![change3](https://user-images.githubusercontent.com/46671821/71561564-9e63bc80-2a78-11ea-8832-7b7fe8e6e4ee.png)

[tv4channels-CodeForChanges.txt](https://github.com/retrospect-addon/plugin.video.retrospect/files/4008464/tv4channels-CodeForChanges.txt)

### Additional context

Thanks for a great addon, daily using Retrospect.
Regards Mats

**Comment by basrieter** [comment]
Thanks for the extensive request with code!  

- [x] Add info on when episode expire. (also in #1269) --> **See that issue**
- [x] Add three dots to extra folders. --> _It makes no sense to include that here. They only exist to hack/fix messed up sorting._
- [ ] Change display name for program title.
- [x] Display Fanart to Program, Season and Episodes. (also in #1268) --> **See that issue**
- [ ] Add Tags to TvShows.
- [ ] Change Swedish language file strings.po --> **@snaah and @sopor need to comment on this. I already changed this soooooo often**. 
- [x] Remove date on program folder name list. --> Just did that for Kodi Leia and up (did not work before).

**Comment by basrieter** [comment]
Please use this zip and manually replace the Retrospect files with the newer versions inside the zip. Finally restart Kodi. It should contain the "checked" items.

[retrospect-patch-20191229.231137.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/4008629/retrospect-patch-20191229.231137.zip)

**Comment by matsarv** [comment]
Regarding " Add three dots to extra folders":
As you mention it messes up sorting if the dots are not there.
I have linked all search pages in Retrospect Favorites. Without the dots the TV4 channels will end up far from the other search links. This is the look with the dots. (When the listing brakes, often the search is working)

![Image4](https://user-images.githubusercontent.com/46671821/71563638-5d2cd600-2a93-11ea-82d1-adca2a14db8c.png)

Regarding "Add Tags to TvShows" and the language file:
I have tried to fins some common name between channels. 

[Retrospect]
![change5](https://user-images.githubusercontent.com/46671821/71563728-9c0f5b80-2a94-11ea-8073-481cb1cd389a.png)

[Webben]
![change6](https://user-images.githubusercontent.com/46671821/71563730-9fa2e280-2a94-11ea-9283-ced61026010a.png)

## retrospect-patch-20191229.231137.zip
I did a quick update of all the files from "retrospect-patch-20191229.231137.zip" to check the changes.
Retrospect didn't start. What i could see, the "chn_svt.py" dit not compile to "chn_svt.pyo".

It's getting to late so I will look into this tomorrow

**Comment by basrieter** [comment]
I just tried this zip on my home Kodi and phone and it worked on both devices. So double check the zip. You cannot install it from zip but need to manually replace the original files with the ones from the zip.

**Comment by matsarv** [comment]
I have now tested the code and all marked changes above is working OK. 

I did find two small enhancements when I checked the changes.

TV4: Add "set_info_label" to show duration i a small black box at bottom
This is used in both SVT and SBS.
![time1](https://user-images.githubusercontent.com/46671821/71583676-c4886b80-2b0f-11ea-93a8-ec07e0c5e26f.png)


SBS: Include title in the item.name for the Show
This is used in both SVT and TV4.
![show1](https://user-images.githubusercontent.com/46671821/71583719-f00b5600-2b0f-11ea-8071-cbe6312709fc.png)

Here comes the code for the changes:
[showandduration.txt](https://github.com/retrospect-addon/plugin.video.retrospect/files/4009869/showandduration.txt)

PS. 
TV4: Please add three dots to extra folders

**Comment by matsarv** [comment]
The Layout will change after adding \lib\plugin.py (also in #1268)

By removing "episodes" or use "tvshows" in "plugin.py" it's will alter the layout in a bad way.

contentType = "episodes"
![contentType-episodes](https://user-images.githubusercontent.com/46671821/71589621-c8bf8380-2b25-11ea-9b24-f13dbfca6b56.png)

All images from channels are in rectanular shape and will fit in the layout used with "episodes". It will display 18 boxes. This looks very good.

contentType = "tvshows"
![contentType-tvshows](https://user-images.githubusercontent.com/46671821/71589630-d1b05500-2b25-11ea-9e79-d7b2f0ef90fe.png)

The layout for images in "tvshows" are in square box and this will crop the images so the text will dissapear at left and right. It will only display 12 boxes.

It will also change the default view settings in Retrospect, and that is not any good.

Please reinsert the contentType "episodes" in plugin.py
        self.contentType = "episodes"

**Comment by basrieter** [comment]
> The Layout will change after adding \lib\plugin.py (also in #1268)
> 
> By removing "episodes" or use "tvshows" in "plugin.py" it's will alter the layout in a bad way.
> 
> contentType = "episodes"
> ![contentType-episodes](https://user-images.githubusercontent.com/46671821/71589621-c8bf8380-2b25-11ea-9b24-f13dbfca6b56.png)
> 
> All images from channels are in rectanular shape and will fit in the layout used with "episodes". It will display 18 boxes. This looks very good.
> 
> contentType = "tvshows"
> ![contentType-tvshows](https://user-images.githubusercontent.com/46671821/71589630-d1b05500-2b25-11ea-9e79-d7b2f0ef90fe.png)
> 
> The layout for images in "tvshows" are in square box and this will crop the images so the text will dissapear at left and right. It will only display 12 boxes.
> 
> It will also change the default view settings in Retrospect, and that is not any good.
> 
> Please reinsert the contentType "episodes" in plugin.py
> self.contentType = "episodes"

You need to tell me where you see this (how do I navigate to that) as I already reverted that in the plugin.py I added here above.

**Comment by basrieter** [comment]
> I have now tested the code and all marked changes above is working OK.
> 
> I did find two small enhancements when I checked the changes.
> 
> TV4: Add "set_info_label" to show duration i a small black box at bottom
> This is used in both SVT and SBS.
> ![time1](https://user-images.githubusercontent.com/46671821/71583676-c4886b80-2b0f-11ea-93a8-ec07e0c5e26f.png)
> 
> SBS: Include title in the item.name for the Show
> This is used in both SVT and TV4.
> ![show1](https://user-images.githubusercontent.com/46671821/71583719-f00b5600-2b0f-11ea-8071-cbe6312709fc.png)
> 
> Here comes the code for the changes:
> [showandduration.txt](https://github.com/retrospect-addon/plugin.video.retrospect/files/4009869/showandduration.txt)
> 
> PS.
> TV4: Please add three dots to extra folders

I added the duration. The name of the show will only included in the listings that contain multiple shows. The fact that SVT/TV4 does how them is because they include it in their metadata. So that I won't change.

**Comment by matsarv** [comment]
> The Layout will change after adding \lib\plugin.py (also in #1268)
> By removing "episodes" or use "tvshows" in "plugin.py" it's will alter the layout in a bad way.
> contentType = "episodes"
> 
> All images from channels are in rectanular shape and will fit in the layout used with "episodes". It will display 18 boxes. This looks very good.
> contentType = "tvshows"
> 
> The layout for images in "tvshows" are in square box and this will crop the images so the text will dissapear at left and right. It will only display 12 boxes.
> It will also change the default view settings in Retrospect, and that is not any good.
> Please reinsert the contentType "episodes" in plugin.py
> self.contentType = "episodes"
> 
> You need to tell me where you see this (how do I navigate to that) as I already reverted that in the plugin.py I added here above.

In the attached zip, retrospect-patch-20191229.231137.zip on row 61 in plugin.py the setting is remarked, 
# self.contentType = "tvshows"

Just checked again, it is not enough to change the above to back to "episodes". I had to pick the plugin.py from 5.1.3 to get the old layout back.
If you have new zip with latest changes, i could try that.

**Comment by Snaah** [comment]
@matsarv Really nice enhancements!

strings.po: Some of the changes you suggest were [discussed thoroughly before](https://github.com/retrospect-addon/plugin.video.retrospect/issues/1217). Could you create a new issue with your suggestions to discuss this? It will get messy here.

**Comment by basrieter** [comment]
> In the attached zip, retrospect-patch-20191229.231137.zip on row 61 in plugin.py the setting is remarked,
> 
> # self.contentType = "tvshows"
> Just checked again, it is not enough to change the above to back to "episodes". I had to pick the plugin.py from 5.1.3 to get the old layout back.
> If you have new zip with latest changes, i could try that.

I know it is commented, because I hardcoded them now for all folders listings to be "episodes", but for the channel listing it is "tvshows" now.  So please tell me exactly how you navigate to the situation where you think it is not OK? Because for me, it all looks OK on my end. 

Keep in mind that every change in Python files require a Kodi restart because Retrospect uses the caching of the language-invoker in Kodi.

**Comment by basrieter** [comment]
@matsarv try this favourites.py:

[favourites.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/4010627/favourites.zip)

**Comment by matsarv** [comment]
I have compared the 5.1.3 and the new one. I can see what you have done. The channel listing will now use "tvshows" and the rest will use "episodes". This is OK since all channel images in Retrospect are square and looks nice with this. (I have created new rectangled images for channel images for the "episodes" layout, so they don't look so nice anymore, but this is my problem to handle, edit plugin.py or make new images). This problem is now solved.

I will have a look at favorites.py

@Snaah I will start a new issue so we can discuss this, next year!

**Comment by matsarv** [comment]
If I changed the code as below in favorites.py it removes the dots (the :. is not present and \a.: needs to be removed)
```
            # clean up the .: from titles
            if ".:" in item.name:
                item.name = item.name.strip("\a.: ")
```
With the above changes , it works for me.

**Comment by basrieter** [comment]
Great! So for now:

- [x] Add info on when episode expire. (also in #1269) --> **See that issue**
- [x] Add three dots to extra folders. --> _Fixed in Favourite listing_
- [x] Change display name for program title.
- [x] Display Fanart to Program, Season and Episodes. (also in #1268) --> **See that issue**
- [ ] ~~Add Tags to TvShows.~~  --> **but it only shows the TV Shows?**
- [ ] Change Swedish language file strings.po --> **@snaah and @sopor need to comment on this. I already changed this soooooo often**. 
- [x] Remove date on program folder name list. --> Just did that for Kodi Leia and up (did not work before).

**Comment by basrieter** [comment]
Will be in the next version.

**Comment by Snaah** [comment]
@matsarv Perfect! I agree with you on most. 

While all these changes already are underway for TV4 Play, I might as well slip in two more instead of new issues:

1. Retrospect already has the Categories (Kategorier). Could we also have the sections listed on the start page of tv4play.se, like Sista chansen (Last chance), Långfilm på TV4 Play (Movies on TV4 Play) and Välgjorda dokumentärer (Well-made documentaries).

2. I suggest to revert having the extra step of "TV-program" to get to the listings.

Happy New Year!

**Comment by basrieter** [comment]
> @matsarv Perfect! I agree with you on most.
> 
> While all these changes already are underway for TV4 Play, I might as well slip in two more instead of new issues:
> 
> 1. Retrospect already has the Categories (Kategorier). Could we also have the sections listed on the start page of tv4play.se, like Sista chansen (Last chance), Långfilm på TV4 Play (Movies on TV4 Play) and Välgjorda dokumentärer (Well-made documentaries).
> 2. I suggest to revert having the extra step of "TV-program" to get to the listings.
> 
> Happy New Year!

1. I don't understand this one.
2. Nope: as already mentioned before: I will most likely move most channels that have multiple selection options (Progams A-Z, Categories, Most Recent) to this format, instead of having those "special" folders listed at the top of a long list of programs.

**Comment by matsarv** [comment]
> @matsarv Perfect! I agree with you on most.
> While all these changes already are underway for TV4 Play, I might as well slip in two more instead of new issues:
> 
> Retrospect already has the Categories (Kategorier). Could we also have the sections listed on the start page of tv4play.se, like Sista chansen (Last chance), Långfilm på TV4 Play (Movies on TV4 Play) and Välgjorda dokumentärer (Well-made documentaries).
> I suggest to revert having the extra step of "TV-program" to get to the listings.
> 
> Happy New Year!
> 
> 
> I don't understand this one.
> Nope: as already mentioned before: I will most likely move most channels that have multiple selection options (Progams A-Z, Categories, Most Recent, etc) to this format, instead of having those "special" folders listed at the top of a long list of programs.

2. I agree. I really wait for the program list on SVT Play moves to a Program A-Ö folder. It takes forever on a Raspberry or Android

**Comment by basrieter** [comment]
> 1. I agree. I really wait for the program list on SVT Play moves to a Program A-Ö folder. It takes forever on a Raspberry or Android
This is one of the reasons.

**Comment by Snaah** [comment]
1. Retrospect shows the Kategorier, which are in the top menu: 
![image](https://user-images.githubusercontent.com/1334819/71627817-b9573d80-2bec-11ea-8e25-3431e28ac49a.png)

But it does not show the sections/tags further down on the starting page:
![image](https://user-images.githubusercontent.com/1334819/71627856-f4f20780-2bec-11ea-95c4-d4aeb0d9665d.png)
![image](https://user-images.githubusercontent.com/1334819/71627888-181cb700-2bed-11ea-9b22-e4a59bc06c51.png)

2. Doesn't the option "Group list if it exceeds # folders" solve that problem? On all my devices, including Android and Android TV, I don't think the loading time is too long. But that depends on how long "forever" is. :) Could a solution be to move the programs without folders to a separate folder?

**Comment by basrieter** [comment]
Those are not in the main API I call. So for now they won't be in there. Please create a new issue for this if you figure out what API call produces these main page categories and their content.

**Comment by basrieter** [comment]
Oh, and the "Group By" is only a display thing. It will still retrieve all data and create all possible list items. So there is no speed improvement at all.

**Comment by Snaah** [comment]
APIs are over my head. "Mest sedda programmen", a "section" from the start page, is already in Retrospect. Strange that TV4 doesn't have the rest of the "sections" from the start page in its API.

Ok.

**Comment by matsarv** [comment]
Since it's not release I will add this. We introduced a small bug here.
We missed to add the episone_text if i was present.
Both Season 1 and 2 was missing episode text.

[tv4episode-TestCode.txt](https://github.com/retrospect-addon/plugin.video.retrospect/files/4022432/tv4episode-TestCode.txt) (may be improved)

Below is how it look when the code changed. Checked around,  many of program had episode text.

![tv4episode](https://user-images.githubusercontent.com/46671821/71771522-a1f5b880-2f3c-11ea-927f-b87284abebfd.png)

**Comment by basrieter** [comment]
Exactly this is why I don't like manually tweaking the texts that the stations provide:

```
if is_episodic:
	name_info = name
	name = result_set["title"].split("del")[0]
	name = name.strip()
	episode_split = name_info.replace(name,"")
	episode_find = episode_split.find("-")
	if (5 < episode_find < 9):
		episode_name = episode_split.split("-")[1]
		episode_name = episode_name.strip() 
		name = "{} - s{:02d}e{:02d} - {}".format(name, season, episode, episode_name)
	else:
		name = "{} - s{:02d}e{:02d}".format(name, season, episode)

```

We fix it for this specific case, but miss out on many others that might exist. But let me check.

**Comment by basrieter** [comment]
Try this:

[chn_tv4se.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/4022531/chn_tv4se.zip)

**Comment by matsarv** [comment]
Checked many program and it looking really good.
